"""Initial models

Revision ID: 697f4a43d422
Revises: 
Create Date: 2025-05-19 16:23:50.497294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697f4a43d422'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pereval_added',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('new', 'pending', 'accepted', 'rejected', name='status'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coord_id', sa.Integer(), nullable=True),
    sa.Column('beauty_title', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('other_titles', sa.String(length=256), nullable=True),
    sa.Column('connect', sa.String(length=128), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('level_winter', sa.Enum('one_a', 'one_b', 'two_a', 'two_b', 'three_a', 'three_b', name='level'), nullable=True),
    sa.Column('level_spring', sa.Enum('one_a', 'one_b', 'two_a', 'two_b', 'three_a', 'three_b', name='level'), nullable=True),
    sa.Column('level_summer', sa.Enum('one_a', 'one_b', 'two_a', 'two_b', 'three_a', 'three_b', name='level'), nullable=True),
    sa.Column('level_autumn', sa.Enum('one_a', 'one_b', 'two_a', 'two_b', 'three_a', 'three_b', name='level'), nullable=True),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_added_id'), 'pereval_added', ['id'], unique=False)
    op.create_table('pereval_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pereval_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['pereval_id'], ['pereval_added.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_images_id'), 'pereval_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pereval_images_id'), table_name='pereval_images')
    op.drop_table('pereval_images')
    op.drop_index(op.f('ix_pereval_added_id'), table_name='pereval_added')
    op.drop_table('pereval_added')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
